### PR TITLE
Node/Express - Lesson 10: Jobs API Part 2

### PR DESCRIPTION
**Pull request by devUser110**
app.js - added extra security packages

controllers/jobs.js - added functionality for getAllJobs, getJob, updateJob, and deleteJob methods

middleware/error-handler.js - added checks for validation error, error code 11000, and cast error

models/User.js - fixed a typo

.node-version - specified node version for render deployment

### CODE REVIEW

**Comment by olearyma** [comment]
Everything looks fine with your jobs api and worked for me locally.  Please share the link to your api running at onrender.com

**Comment by devUser110** [comment]
Hi Mike,

The link to my render deployment: https://jobs-api-dev-prod.onrender.com

The homepage says "Route does not exist", should I add:

app.get("/", (req, res) => {
  res.send(<p>Jobs API</p>);
});

to app.js and redeploy and create a new pull request? Otherwise, my API is
working in Postman.

Thanks,

Devon

**Comment by olearyma** [comment]
Yes, that should fix it.  You can refer to the code in the final folder:
https://github.com/Code-the-Dream-School/node-express-course/blob/main/06-jobs-api/final/app.js

**Comment by devUser110** [comment]
I updated app.js and redeployed the API to render

**Review by olearyma — APPROVED** [review]
Everything works, nice job.

**Pull request merged**
